/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Banner = {
  _type: "banner";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?:
      | "normal"
      | "h1"
      | "h2"
      | "h3"
      | "h4"
      | "h5"
      | "h6"
      | "h1Centered"
      | "h2Centered"
      | "h3Centered"
      | "h4Centered"
      | "centered";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ImagesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "images";
};

export type ImagesRef = {
  _type: "imagesRef";
  images?: ImagesReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Images = {
  _id: string;
  _type: "images";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type VideoRef = {
  _type: "videoRef";
  video?: VideoReference;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  alt?: string;
  autoplay?: boolean;
  muted?: boolean;
};

export type Metadata = {
  _id: string;
  _type: "metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle?: string;
  description?: string;
  language?: "de" | "en";
};

export type HeadlineWithDate = {
  _type: "headlineWithDate";
  date?: string;
  title?: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type NavDropdownItem = {
  _type: "navDropdownItem";
  label?: string;
  page?: PageReference;
};

export type NavDropdown = {
  _type: "navDropdown";
  label?: string;
  items?: Array<
    {
      _key: string;
    } & NavDropdownItem
  >;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  page?: PageReference;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<
    | ({
        _key: string;
      } & NavLink)
    | ({
        _key: string;
      } & NavDropdown)
  >;
  language?: "de" | "en";
};

export type ImageGallery = {
  _type: "imageGallery";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type ColumnText = {
  _type: "columnText";
  col1?: BlockContent;
  col2?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?:
        | "normal"
        | "h1"
        | "h2"
        | "h3"
        | "h4"
        | "h5"
        | "h6"
        | "h1Centered"
        | "h2Centered"
        | "h3Centered"
        | "h4Centered"
        | "centered";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | ({
            _key: string;
          } & Anchor)
        | ({
            _key: string;
          } & Link)
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ColumnText)
  | ({
      _key: string;
    } & ImageGallery)
  | ({
      _key: string;
    } & ImagesRef)
  | ({
      _key: string;
    } & Table)
  | ({
      _key: string;
    } & VideoRef)
  | ({
      _key: string;
    } & HeadlineWithDate)
  | ({
      _key: string;
    } & Banner)
>;

export type CalloutSection = {
  _type: "calloutSection";
  title?: string;
  content?: SectionContent;
};

export type TwoColumnSection = {
  _type: "twoColumnSection";
  left?: SectionContent;
  right?: SectionContent;
};

export type QuoteSection = {
  _type: "quoteSection";
  content?: SectionContent;
  attribution?: string;
};

export type TextSection = {
  _type: "textSection";
  content?: SectionContent;
};

export type SectionContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Link = {
  _type: "link";
  href?: string;
};

export type Anchor = {
  _type: "anchor";
  label?: string;
  slug?: Slug;
  hidden?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: PageReference;
  language?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle?: string;
  description?: string;
  language?: "de" | "en";
  path?: string;
  isHome?: boolean;
  studioGroup?: string;
  sections?: Array<
    | ({
        _key: string;
      } & TextSection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & TwoColumnSection)
    | ({
        _key: string;
      } & CalloutSection)
  >;
};

export type Table = {
  _type: "table";
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Banner
  | ImagesReference
  | ImagesRef
  | SanityImageAssetReference
  | Images
  | SanityImageCrop
  | SanityImageHotspot
  | VideoReference
  | VideoRef
  | SanityFileAssetReference
  | Video
  | Metadata
  | HeadlineWithDate
  | PageReference
  | NavDropdownItem
  | NavDropdown
  | NavLink
  | Navigation
  | ImageGallery
  | ColumnText
  | BlockContent
  | CalloutSection
  | TwoColumnSection
  | QuoteSection
  | TextSection
  | SectionContent
  | Link
  | Anchor
  | Slug
  | TranslationMetadata
  | InternationalizedArrayReference
  | InternationalizedArrayReferenceValue
  | Page
  | Table
  | TableRow
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: metadataQuery
// Query: *[_type == "metadata" && language == $lang][0]
export type MetadataQueryResult = {
  _id: string;
  _type: "metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle?: string;
  description?: string;
  language?: "de" | "en";
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: pathsQuery
// Query: *[_type == "page" && defined(language)]{    language,    path,    isHome  }
export type PathsQueryResult = Array<{
  language: "de" | "en";
  path: string | null;
  isHome: boolean | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: allPagesQuery
// Query: *[_type == "page" && language == $lang] | order(isHome desc, path asc) {    _id,    title,    path,    isHome,    language  }
export type AllPagesQueryResult = Array<{
  _id: string;
  title: string | null;
  path: string | null;
  isHome: boolean | null;
  language: "de" | "en" | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: pageByPathQuery
// Query: *[    _type == "page" &&    language == $lang &&    (      ($path == "" && isHome == true) ||      ($path != "" && path == $path && isHome != true)    )  ][0]{    _id,    title,    seoTitle,    description,    path,    isHome,    language,    sections[]{      _key,      _type,      content,      attribution,      title,      left,      right    },    "translations": *[_type == "translation.metadata" && references(^._id)][0]      .translations[]{        language,        "page": value->{          _id,          title,          path,          isHome,          language        }      }  }
export type PageByPathQueryResult = {
  _id: string;
  title: string | null;
  seoTitle: string | null;
  description: string | null;
  path: string | null;
  isHome: boolean | null;
  language: "de" | "en" | null;
  sections: Array<
    | {
        _key: string;
        _type: "calloutSection";
        content: SectionContent | null;
        attribution: null;
        title: string | null;
        left: null;
        right: null;
      }
    | {
        _key: string;
        _type: "quoteSection";
        content: SectionContent | null;
        attribution: string | null;
        title: null;
        left: null;
        right: null;
      }
    | {
        _key: string;
        _type: "textSection";
        content: SectionContent | null;
        attribution: null;
        title: null;
        left: null;
        right: null;
      }
    | {
        _key: string;
        _type: "twoColumnSection";
        content: null;
        attribution: null;
        title: null;
        left: SectionContent | null;
        right: SectionContent | null;
      }
  > | null;
  translations: Array<{
    language: string | null;
    page: {
      _id: string;
      title: string | null;
      path: string | null;
      isHome: boolean | null;
      language: "de" | "en" | null;
    } | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "metadata" && language == $lang][0]\n': MetadataQueryResult;
    '\n  *[_type == "page" && defined(language)]{\n    language,\n    path,\n    isHome\n  }\n': PathsQueryResult;
    '\n  *[_type == "page" && language == $lang] | order(isHome desc, path asc) {\n    _id,\n    title,\n    path,\n    isHome,\n    language\n  }\n': AllPagesQueryResult;
    '\n  *[\n    _type == "page" &&\n    language == $lang &&\n    (\n      ($path == "" && isHome == true) ||\n      ($path != "" && path == $path && isHome != true)\n    )\n  ][0]{\n    _id,\n    title,\n    seoTitle,\n    description,\n    path,\n    isHome,\n    language,\n    sections[]{\n      _key,\n      _type,\n      content,\n      attribution,\n      title,\n      left,\n      right\n    },\n    "translations": *[_type == "translation.metadata" && references(^._id)][0]\n      .translations[]{\n        language,\n        "page": value->{\n          _id,\n          title,\n          path,\n          isHome,\n          language\n        }\n      }\n  }\n': PageByPathQueryResult;
  }
}
