/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Banner = {
  _type: "banner";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?:
      | "normal"
      | "h1"
      | "h2"
      | "h3"
      | "h4"
      | "h5"
      | "h6"
      | "h1Centered"
      | "centered";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ImagesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "images";
};

export type ImagesRef = {
  _type: "imagesRef";
  images?: ImagesReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Images = {
  _id: string;
  _type: "images";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type VideoRef = {
  _type: "videoRef";
  video?: VideoReference;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  alt?: string;
  autoplay?: boolean;
  muted?: boolean;
};

export type Metadata = {
  _id: string;
  _type: "metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle?: string;
  description?: string;
  language?: "de" | "en";
};

export type HeadlineWithDate = {
  _type: "headlineWithDate";
  date?: string;
  title?: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type NavDropdownItem = {
  _type: "navDropdownItem";
  label?: string;
  page?: PageReference;
};

export type NavDropdown = {
  _type: "navDropdown";
  label?: string;
  items?: Array<
    {
      _key: string;
    } & NavDropdownItem
  >;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  page?: PageReference;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<
    | ({
        _key: string;
      } & NavLink)
    | ({
        _key: string;
      } & NavDropdown)
  >;
  language?: "de" | "en";
};

export type ImageGallery = {
  _type: "imageGallery";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type ColumnText = {
  _type: "columnText";
  col1?: BlockContent;
  col2?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?:
        | "normal"
        | "h1"
        | "h2"
        | "h3"
        | "h4"
        | "h5"
        | "h6"
        | "h1Centered"
        | "centered";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | ({
            _key: string;
          } & Anchor)
        | ({
            _key: string;
          } & Link)
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ColumnText)
  | ({
      _key: string;
    } & ImageGallery)
  | ({
      _key: string;
    } & ImagesRef)
  | ({
      _key: string;
    } & Table)
  | ({
      _key: string;
    } & VideoRef)
  | ({
      _key: string;
    } & HeadlineWithDate)
  | ({
      _key: string;
    } & Banner)
>;

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle?: string;
  description?: string;
  language?: "de" | "en";
  slug?: Slug;
  isHome?: boolean;
  showPrevNextNav?: boolean;
  content?: BlockContent;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Link = {
  _type: "link";
  href?: string;
};

export type Anchor = {
  _type: "anchor";
  label?: string;
  slug?: Slug;
  hidden?: boolean;
};

export type Table = {
  _type: "table";
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Banner
  | ImagesReference
  | ImagesRef
  | SanityImageAssetReference
  | Images
  | SanityImageCrop
  | SanityImageHotspot
  | VideoReference
  | VideoRef
  | SanityFileAssetReference
  | Video
  | Metadata
  | HeadlineWithDate
  | PageReference
  | NavDropdownItem
  | NavDropdown
  | NavLink
  | Navigation
  | ImageGallery
  | ColumnText
  | BlockContent
  | Page
  | Slug
  | Link
  | Anchor
  | Table
  | TableRow
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/sanity/queries.ts
// Variable: metadataQuery
// Query: *[_type == "metadata" && language == $lang][0]
export type MetadataQueryResult = {
  _id: string;
  _type: "metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle?: string;
  description?: string;
  language?: "de" | "en";
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: slugsQuery
// Query: *[    _type == "page" &&    defined(slug.current) &&    isHome != true  ]{    "slug": slug.current,    language  }
export type SlugsQueryResult = Array<{
  slug: string | null;
  language: "de" | "en" | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: homepageQuery
// Query: *[_type == "page" && isHome == true && language == $lang][0]{    _id,    title,    showPrevNextNav,    content[]{      ...,      _type == "videoRef" => {        ...,        video->{          caption,          title,          muted,          autoplay,          "url": file.asset->url,          "poster": poster.asset->url        }      },      _type == "imagesRef" => {        ...,        images->{          ...        }      }    }  }
export type HomepageQueryResult = {
  _id: string;
  title: string | null;
  showPrevNextNav: boolean | null;
  content: Array<
    | {
        _key: string;
        _type: "banner";
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "centered"
            | "h1"
            | "h1Centered"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "centered"
          | "h1"
          | "h1Centered"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & Anchor)
          | ({
              _key: string;
            } & Link)
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "columnText";
        col1?: BlockContent;
        col2?: BlockContent;
      }
    | {
        _key: string;
        _type: "headlineWithDate";
        date?: string;
        title?: string;
      }
    | {
        _key: string;
        _type: "imageGallery";
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          caption?: string;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "imagesRef";
        images: {
          _id: string;
          _type: "images";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          images?: Array<{
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            caption?: string;
            alt?: string;
            _type: "image";
            _key: string;
          }>;
        } | null;
      }
    | {
        _key: string;
        _type: "table";
        rows?: Array<
          {
            _key: string;
          } & TableRow
        >;
      }
    | {
        _key: string;
        _type: "videoRef";
        video: {
          caption: string | null;
          title: string | null;
          muted: boolean | null;
          autoplay: boolean | null;
          url: string | null;
          poster: string | null;
        } | null;
      }
  > | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: pageBySlugQuery
// Query: {    "page": *[      _type == "page" &&      slug.current == $slug &&       isHome != true &&      language == $lang    ][0]{      _id,      title,      seoTitle,      description,      slug,            showPrevNextNav,      content[]{        ...,        _type == "videoRef" => {          ...,          video->{            caption,            title,            muted,            autoplay,            "url": file.asset->url,            "poster": poster.asset->url          }        },        _type == "imagesRef" => {          ...,          "images": images->        }      },      "slug": slug.current,      "navContext": *[_type == "navigation" && language == $lang][0]{        "dropdown": items[          _type == "navDropdown" &&           (count(items[page._ref == ^.^.^._id]) > 0)        ][0] {          ...,          items[]{            ...,            "slug": page->slug.current          }        }      }    }  }
export type PageBySlugQueryResult = {
  page: {
    _id: string;
    title: string | null;
    seoTitle: string | null;
    description: string | null;
    slug: string | null;
    showPrevNextNav: boolean | null;
    content: Array<
      | {
          _key: string;
          _type: "banner";
          content?: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "centered"
              | "h1"
              | "h1Centered"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }>;
        }
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "centered"
            | "h1"
            | "h1Centered"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | ({
                _key: string;
              } & Anchor)
            | ({
                _key: string;
              } & Link)
          >;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          _key: string;
          _type: "columnText";
          col1?: BlockContent;
          col2?: BlockContent;
        }
      | {
          _key: string;
          _type: "headlineWithDate";
          date?: string;
          title?: string;
        }
      | {
          _key: string;
          _type: "imageGallery";
          images?: Array<{
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            caption?: string;
            alt?: string;
            _type: "image";
            _key: string;
          }>;
        }
      | {
          _key: string;
          _type: "imagesRef";
          images: {
            _id: string;
            _type: "images";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            images?: Array<{
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              caption?: string;
              alt?: string;
              _type: "image";
              _key: string;
            }>;
          } | null;
        }
      | {
          _key: string;
          _type: "table";
          rows?: Array<
            {
              _key: string;
            } & TableRow
          >;
        }
      | {
          _key: string;
          _type: "videoRef";
          video: {
            caption: string | null;
            title: string | null;
            muted: boolean | null;
            autoplay: boolean | null;
            url: string | null;
            poster: string | null;
          } | null;
        }
    > | null;
    navContext: {
      dropdown: {
        _key: string;
        _type: "navDropdown";
        label?: string;
        items: Array<{
          _key: string;
          _type: "navDropdownItem";
          label?: string;
          page?: PageReference;
          slug: string | null;
        }> | null;
      } | null;
    } | null;
  } | null;
};

// Source: ../web/src/sanity/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation" && language == $lang][0]{    items[]{      _type,      _key,      label,      _type == "navLink" => {        "slug": page->slug.current      },      _type == "navDropdown" => {        items[]{          label,          _key,          "slug": page->slug.current        }      }    }  }
export type NavigationQueryResult = {
  items: Array<
    | {
        _type: "navDropdown";
        _key: string;
        label: string | null;
        items: Array<{
          label: string | null;
          _key: string;
          slug: string | null;
        }> | null;
      }
    | {
        _type: "navLink";
        _key: string;
        label: string | null;
        slug: string | null;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "metadata" && language == $lang][0]\n': MetadataQueryResult;
    '\n  *[\n    _type == "page" &&\n    defined(slug.current) &&\n    isHome != true\n  ]{\n    "slug": slug.current,\n    language\n  }\n': SlugsQueryResult;
    '\n  *[_type == "page" && isHome == true && language == $lang][0]{\n    _id,\n    title,\n    showPrevNextNav,\n    content[]{\n      ...,\n      _type == "videoRef" => {\n        ...,\n        video->{\n          caption,\n          title,\n          muted,\n          autoplay,\n          "url": file.asset->url,\n          "poster": poster.asset->url\n        }\n      },\n      _type == "imagesRef" => {\n        ...,\n        images->{\n          ...\n        }\n      }\n    }\n  }\n': HomepageQueryResult;
    '\n  {\n    "page": *[\n      _type == "page" &&\n      slug.current == $slug && \n      isHome != true &&\n      language == $lang\n    ][0]{\n      _id,\n      title,\n      seoTitle,\n      description,\n      slug,      \n      showPrevNextNav,\n      content[]{\n        ...,\n        _type == "videoRef" => {\n          ...,\n          video->{\n            caption,\n            title,\n            muted,\n            autoplay,\n            "url": file.asset->url,\n            "poster": poster.asset->url\n          }\n        },\n        _type == "imagesRef" => {\n          ...,\n          "images": images->\n        }\n      },\n      "slug": slug.current,\n      "navContext": *[_type == "navigation" && language == $lang][0]{\n        "dropdown": items[\n          _type == "navDropdown" && \n          (count(items[page._ref == ^.^.^._id]) > 0)\n        ][0] {\n          ...,\n          items[]{\n            ...,\n            "slug": page->slug.current\n          }\n        }\n      }\n    }\n  }\n': PageBySlugQueryResult;
    '\n  *[_type == "navigation" && language == $lang][0]{\n    items[]{\n      _type,\n      _key,\n      label,\n      _type == "navLink" => {\n        "slug": page->slug.current\n      },\n      _type == "navDropdown" => {\n        items[]{\n          label,\n          _key,\n          "slug": page->slug.current\n        }\n      }\n    }\n  }\n': NavigationQueryResult;
  }
}
